' UC-03

class TechMap $uc03 {}

class TechStage $uc03 {}

class ParamValue $uc03 {
	value
}

class WorkStationBooking $uc03 {
	start: Timestamp
	finish: Timestamp
}

class WorkStation $uc03 {
	name: string
}

class WorkStationType $uc03 {
	name: string
}

enum ParamType {
	BOOLEAN
	NUMBER
	STRING
	TIMESTAMP
}

class Nomenclature $uc03 {
	name: string
}

class Order $uc03 {}

class OrderItem $uc03 {
	quantity: int
}

class OrderItemSubquantity $uc03 {
	quantity: int
}

TechMap "1" *-- "1..*" OrderItemSubquantity
TechMap "1" *-- "*" TechStage

OrderItemSubquantity "*" o-- "1" OrderItem

Order "1" *-- "*" OrderItem

OrderItem "*" -- "1" Nomenclature

Nomenclature "*" -- "*" WorkStationType

WorkStationType [name: string] -- "0..1" ParamType

WorkStation "1" -- "*" WorkStationBooking

TechStage "0..1" o-l- "1" WorkStationBooking
TechStage [name: string] -- "0..1" ParamValue
