' UC-03

class TechMap $uc03 {}
class TechStage $uc03 {}

class WorkStationBooking $uc03 {
	start: Timestamp
	finish: Timestamp
}

class WorkStation $uc03 {}
class WorkStationType $uc03 {}
class WorkStationParamType $uc03 {}

class WorkStationParam $uc03 {
	value
}

class Nomenclature $uc03 {
	name: string
}

class Customer $uc03 {}

class Order $uc03 {}
class OrderItem $uc03 {
	quantity: int
}

class OrderItemSubquantity $uc03 {
	quantity: int
}

TechMap "1" -- "1..*" OrderItemSubquantity
TechMap "1" --  TechStage

OrderItemSubquantity -- "1" OrderItem

TechStage [paramName: string] -- WorkStationParam
TechStage "0..1" - "1" WorkStationBooking

Customer "1" -- Order
Order "1" -- OrderItem
OrderItem -- "1" Nomenclature

Nomenclature "1" -- WorkStationType

WorkStation "1" -- WorkStationBooking
WorkStation - "1" WorkStationType

WorkStationType [paramName: string] -- "0..1" WorkStationParamType

WorkStationParam - "1" WorkStationParamType
