class Order $uc03
Order *--> OrderItem: items

class OrderItem $uc03
OrderItem o--> "1" Nomenclature: nomenclature

class Nomenclature $uc03 {
	- id: int
	- name: string
}
Nomenclature o--> "{ordered}" WorkStationDecl: steps

class WorkStationDecl $uc03 {
	- id: int
	- name: string
}
WorkStationDecl [name: string] *--> WorkStationParamInfo: paramInfos

abstract class WorkStationParamInfo {
	- isMandatory: boolean
	+ isMandatory(): boolean
	+ accept(visitor: WorkStationParamInfoVisitor): void
}
WorkStationParamInfo ..> WorkStationParamInfoVisitor: <<use>>
WorkStationParamInfo <|-- WorkStationBooleanParamInfo
WorkStationParamInfo <|-- WorkStationNumericParamInfo
WorkStationParamInfo <|-- WorkStationStringParamInfo
WorkStationParamInfo <|-- WorkStationTimestampParamInfo

interface WorkStationParamInfoVisitor {
	+ visitBoolean(isMandatory: boolean): void
	+ visitNumber(isMandatory: boolean, range: Range<double>): void
	+ visitString(isMandatory: boolean, pattern: Regex): void
	+ visitTimestamp(isMandatory: boolean, range: Range<Timestamp>): void
}
WorkStationParamInfoVisitor ..> Range
WorkStationParamInfoVisitor <|-- WorkStationParamHtmlFormBuilder

class Range<T> $uc03 {
	- min: Border<T>
	- max: Border<T>
	+ includes(value: T): boolean
}
Range *--> "1" Border: min
Range *--> "1" Border: max

class Border<T> {
	- isInclusive: boolean
	- value: T
	+ checkLower(value: T): boolean
	+ checkUpper(value: T): boolean
}

class WorkStationParamHtmlFormBuilder $uc03 {
	- paramName: string
	- form: HtmlForm
}
note right: Visitor implementation example

class WorkStationBooleanParamInfo $uc03

class WorkStationNumericParamInfo $uc03 {
	- range: Range<double>
}
WorkStationNumericParamInfo *--> Range: range

class WorkStationStringParamInfo $uc03 {
	- pattern: Regex
}

class WorkStationTimestampParamInfo $uc03 {
	- range: Range<Timestamp>
}
WorkStationTimestampParamInfo *--> Range: range

class TechMap $uc03 {
	- customer: Customer
	- creationTimestamp: Timestamp
}
TechMap *--> "1..*" OrderItemSubquantity : items
TechMap *--> "{ordered}" TechStage : stages

class OrderItemSubquantity $uc03 {
	- quantity: int
}
OrderItemSubquantity o--> "1" OrderItem : originalItem

class TechStage $uc03
TechStage [name: string] *--> WorkStationParamValue: paramValues
TechStage *-> "1" WorkStationBooking

interface WorkStationParamValue {
	+ accept(visitor: WorkStationParamValueVisitor): void
}
WorkStationParamValue ..> WorkStationParamValueVisitor: <<use>>
WorkStationParamValue <|-- WorkStationBooleanParamValue
WorkStationParamValue <|-- WorkStationNumericParamValue
WorkStationParamValue <|-- WorkStationStringParamValue
WorkStationParamValue <|-- WorkStationTimestampParamValue

interface WorkStationParamValueVisitor {
	+ visit(value: boolean): void
	+ visit(value: double): void
	+ visit(value: string): void
	+ visit(value: Timestamp): void
}
WorkStationParamValueVisitor <|-- WorkStationParamSqlInsertQueryBuilder

class WorkStationParamSqlInsertQueryBuilder $uc03 {
	- paramName: string
	- query: SqlQuery
}
note right: Visitor implementation example

class WorkStationBooleanParamValue {
	- value: boolean
}

class WorkStationNumericParamValue {
	- value: double
}

class WorkStationStringParamValue {
	- value: string
}

class WorkStationTimestampParamValue {
	- value: Timestamp
}

class WorkStationBooking $uc03 {
	- id: int
	- start: Timestamp
	- finish: Timestamp
}
WorkStationBooking o--> "1" WorkStation

class WorkStation $uc03 {
	- id: int
	- name: string
}
WorkStation o-> "1" WorkStationDecl
